# Generated by Django 3.2.12 on 2022-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_data', '0002_rename_city_id_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
