# Generated by Django 3.2.12 on 2022-02-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_data', '0003_alter_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_tag',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
